Add new notebooks
OpenChemistry/distiller pull request #802
Opened 2023-05-31 14:10 UTC by cjh1

2023-06-03 04:58 UTC, swelborn requested changes

2023-06-03 04:58 UTC, swelborn commented on backend/faust/templates/vacuum_scan_subtract.ipynb.j2
> +    "distiller_path = Path('/global/cfs/cdirs/ncemhub/distiller/')"
this could be done with `settings.NCEMHUB_PATH`

2023-06-03 04:58 UTC, swelborn commented on backend/faust/templates/vacuum_scan_prepare.ipynb.j2
> +    "date = Path('2023.01.13')\n",
should be '{{ scan_created_date }}' instead of `2023.01.13`

2023-06-03 04:58 UTC, swelborn commented on backend/faust/templates/vacuum_scan_subtract.ipynb.j2
> +    "fname = get_scan_path(distiller_path / Path('counted') / Path(date), scan_num)\n",
fname is a tuple here, you'll want to use the same as the other file:

fname, scan_num, scan_id = get_scan_path(distiller_path / Path('counted') / Path(date), scan_num, scan_id=scan_id)

2023-06-03 04:58 UTC, swelborn commented on backend/faust/templates/vacuum_scan_subtract.ipynb.j2
> +    "offsets_path = Path('/mnt/nvme1/percius/microED/2023.05.15/data_scan666_id9913_electrons_centered_offsets.emd')\n",
Maybe store somewhere on CFS?

2023-06-03 04:58 UTC, swelborn commented on backend/faust/templates/vacuum_scan_subtract.ipynb.j2
> +    "offsets_path = Path('/mnt/nvme1/percius/microED/2023.05.15/data_scan666_id9913_electrons_centered_offsets.emd')\n",
Can't get past this point on this notebook, once the file is there I should be able to proceed

2023-06-03 04:58 UTC, swelborn commented on frontend/distiller/src/pages/scan.tsx
>          window.open(`${JUPYTER_USER_REDIRECT_URL}${notebook.path}`, '_blank');
This doesn't have to do with this PR, but right now this is defaulting to opening up a cori shared server and I have to manually switch. Is it possible to default to perlmutter shared node? 

might be a change in jupyterhub... it's this link: `https://jupyter.nersc.gov/hub/user-redirect/lab/tree`

2023-06-03 04:58 UTC, swelborn commented on frontend/distiller/src/pages/scan.tsx
> +          {notebooks && (
Frontend looks good! Could potentially be nicer to not have underscores in the names of the notebooks..

2023-06-03 04:58 UTC, swelborn commented on backend/faust/templates/vacuum_scan_prepare.ipynb.j2
> +    "fg,ax = plt.subplots(1, 2)\n",
I think com2_median and com2_std are undefined here?

2023-06-05 12:49 UTC, cjh1 commented on frontend/distiller/src/pages/scan.tsx
> +          {notebooks && (
I thought about it, but as we use the name to map to the file on disk, having spaces might complicate things.

2023-06-05 12:50 UTC, cjh1 commented on backend/faust/templates/vacuum_scan_prepare.ipynb.j2
> +    "fg,ax = plt.subplots(1, 2)\n",
@ercius

2023-06-05 12:50 UTC, cjh1 commented on backend/faust/templates/vacuum_scan_subtract.ipynb.j2
> +    "offsets_path = Path('/mnt/nvme1/percius/microED/2023.05.15/data_scan666_id9913_electrons_centered_offsets.emd')\n",
@ercius

2023-06-05 13:07 UTC, cjh1 commented on backend/faust/templates/vacuum_scan_subtract.ipynb.j2
> +    "fname = get_scan_path(distiller_path / Path('counted') / Path(date), scan_num)\n",
This is fixed in @ercius latest updates

2023-06-05 13:07 UTC, cjh1 commented on backend/faust/templates/vacuum_scan_subtract.ipynb.j2
> +    "offsets_path = Path('/mnt/nvme1/percius/microED/2023.05.15/data_scan666_id9913_electrons_centered_offsets.emd')\n",
I see this is fixed in @ercius 's updates

2023-06-05 13:11 UTC, cjh1 commented on backend/faust/templates/vacuum_scan_subtract.ipynb.j2
> +    "distiller_path = Path('/global/cfs/cdirs/ncemhub/distiller/')"
Fixed

2023-06-05 19:20 UTC, ercius commented on backend/faust/templates/vacuum_scan_prepare.ipynb.j2
> +    "date = Path('2023.01.13')\n",
Yes. It is ok to change the name. I have just used `date` to make it shorter, but `scan_create_date` is more descriptive

2023-06-05 19:20 UTC, ercius commented on backend/faust/templates/vacuum_scan_subtract.ipynb.j2
> +    "offsets_path = Path('/mnt/nvme1/percius/microED/2023.05.15/data_scan666_id9913_electrons_centered_offsets.emd')\n",
I did not handle this properly in my first iteration. New updates should allow this to work now.

2023-06-05 19:27 UTC, ercius commented on frontend/distiller/src/pages/scan.tsx
>          window.open(`${JUPYTER_USER_REDIRECT_URL}${notebook.path}`, '_blank');
It still opens in Cori today. The Jupyter startup page allows you to launch on Cori and Perlmutter. And when I start on Cori I get a Cori log in node (`@cori`)`. `$SCRATCH` and `$PSCRATCH` are both available.

2023-06-30 19:53 UTC, ercius commented
@cjh1 Not sure where we are at with this. Ready to go at least to test further?

2023-06-30 19:55 UTC, cjh1 commented
Its deployed, so we should merge. Any fixes can go in a follow up PR.

2023-06-30 19:56 UTC, merged